server.port=8081
spring.application.name=auth-service

# H2 Database (local dev)
spring.datasource.url=jdbc:h2:mem:authdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT
app.jwt.secret=dGVzdGRHVnpkR1JsYzNSbFpHVnlkR2x1WjNOaFkzSmxkR2x2YmkxclpYaz0
app.jwt.expiration=86400000

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=185197611345-ejn6t5krdp6h51dh7jrbume2557fuuvq.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8081/login/oauth2/code/google

# Actuator
management.endpoints.web.exposure.include=health,info

# Logging
logging.level.com.app=DEBUG